---========================---
---== LUA MODULE IMPORTS ==---
---========================---
local debugdraw = require "extensions.defold.debug-draw.debug-draw"
local defmath = require "extensions.defold.defmath.defmath"
local lume = require "extensions.external.lume.lume"
local gui_extra = require "extensions.defold.gui_extra.gui_extra"
local monarch = require "extensions.defold.monarch.monarch"
local rc = require "extensions.defold.rendercam.rendercam"
local csv = require "extensions.defold.csv-importer.csv-importer"
local gp = require "gamedata.runtime_gameplay"
local c = require "gamedata.constants"

---========================---
---========================---

local function hflip_object(object_url, direction)

	if direction == 1 then 
		go.set_rotation(vmath.quat_rotation_y(0), object_url)
	elseif direction == -1 then
		go.set_rotation(vmath.quat_rotation_y(math.pi), object_url)
	end

end


---========================---
---========================---

function init(self)
	msg.post(".", "acquire_input_focus")

	-- char control
	self.direction = vmath.vector3()
	self.speed = 5

	self.idle = 0
	self.moving = 0
	self.attacking = 0
	
	-- animation
	self.url = "/spine_test#model"
	self.anim_cur = ""
	self.switch_anim = 1
	self.anim_idle_name = "idle"
	self.anim_move_name = "walk" -- run for the spineboy, walk for the test_ork_001 ("idle" remains "idle" in both cases)
	self.anim_attack_name = "attack_melee_1h"
	
	self.anim_speed_idle = 2
	self.anim_speed_walk = 1.5
	self.anim_speed_attack = 1
	self.anim_blend_duration = 0.15
	
	-- spine_custo
	local nb_slots = #gp.slots
	for i=1,nb_slots do
		spine.set_attachment(self.url, gp.slots[i].name, gp.slots[i].image.."_"..gp.slots[i].id_min)
	end

end

function update(self, dt)

	--====================--
	------ MOVEMENT
	--====================--
	
	-- normalization (not required here but.. who knows)
	if vmath.length_sqr(self.direction) > 1 then
		self.direction = vmath.normalize(self.direction)
	end

	local p = go.get_world_position()
	local movement = self.direction * self.speed
	local p_final = p + movement
	p_final.x, p_final.y = lume.round(p_final.x, 1), lume.round(p_final.y, 1)
	go.set_position(p_final)


	
	--====================--
	------ STATES
	--====================--

	if self.direction.x == 0 then

		if self.attacking > 0 then
			self.idle = 0
			self.moving = 0
			
		else
			self.idle = 1
			self.moving = 0
			self.attacking = 0
		end

	else
		self.moving = 1
		self.idle = 0
		self.attacking = 0
	end


	--====================--
	------ ATTACK
	--====================--

	if self.attacking == 2 then

		self.switch_anim = 0

	end
	
	
	if self.attacking == 1 then

		self.switch_anim = 1
		
		self.attacking = 2

	end

	
	--====================--
	------ ANIMATION
	--====================--

	if self.switch_anim == 1 then

		local blend_duration_value, playback_rate_value, loop_type = 0, self.anim_speed_idle, go.PLAYBACK_LOOP_FORWARD
		
		if self.idle == 1 then
			self.anim_cur = self.anim_idle_name
			blend_duration_value = self.anim_blend_time
			loop_type = go.PLAYBACK_LOOP_FORWARD
		elseif self.moving == 1 then
			self.anim_cur = self.anim_move_name
			playback_rate_value = self.anim_speed_walk
			loop_type = go.PLAYBACK_LOOP_FORWARD
		elseif self.attacking > 0 then
			self.anim_cur = self.anim_attack_name
			playback_rate_value = self.anim_speed_attack
			loop_type = go.PLAYBACK_ONCE_FORWARD
		end
				
		local properties = { blend_duration = blend_duration_value, playback_rate = playback_rate_value }
		spine.play_anim(self.url, self.anim_cur, loop_type, properties)
		print("self.anim_cur = "..self.anim_cur)
		print("loop_type = "..loop_type)

		self.switch_anim = 0
	end

	
	--====================--
	------ ORIENTATION (left-right)
	--====================--
	
	hflip_object(self.url,self.direction.x)


	--====================--
	------ CUSTOMIZATION
	--====================--

	local nb_slots_updated = #gp.slots_updated
	
	if nb_slots_updated > 0 then

		for i=1,#gp.slots_updated do
			--print("slot index => "..gp.slots_updated[i].index)
		end
		
		----[[--
		for i=1,nb_slots_updated do
			local slot_index = gp.slots_updated[i].index
			local nb_slots = #gp.slots
			for j=1,nb_slots do
				if j == slot_index then
					--print("pouet pouet > slot "..j)
					gp.slots[j].id_cur = gp.slots[j].id_cur + 1
					if gp.slots[j].id_cur > gp.slots[j].id_max then
						gp.slots[j].id_cur = gp.slots[j].id_min
					end
					local id_cur = gp.slots[j].id_cur
					local name = gp.slots[j].name
					local image_tag = gp.slots[j].image
					spine.set_attachment(self.url, name, image_tag.."_"..id_cur)
				end
			end
		end

		
		--print("updated ! pouet pouet")
		--]]--
		emptytable(gp.slots_updated)

	end


	--====================--
	------ DEBUG
	--====================--

	local DEBUG_pos_x, DEBUG_pos_y, DEBUG_pos_y_diff = 10,500,15
	debugdraw.text("self.direction.x = "..self.direction.x, DEBUG_pos_x, DEBUG_pos_y, color)
	DEBUG_pos_y = DEBUG_pos_y - DEBUG_pos_y_diff
	debugdraw.text("self.switch_anim = "..self.switch_anim, DEBUG_pos_x, DEBUG_pos_y, color)
	DEBUG_pos_y = DEBUG_pos_y - DEBUG_pos_y_diff*2
	debugdraw.text("self.idle = "..self.idle, DEBUG_pos_x, DEBUG_pos_y, color)
	DEBUG_pos_y = DEBUG_pos_y - DEBUG_pos_y_diff
	debugdraw.text("self.moving = "..self.moving, DEBUG_pos_x, DEBUG_pos_y, color)
	DEBUG_pos_y = DEBUG_pos_y - DEBUG_pos_y_diff
	debugdraw.text("self.attacking = "..self.attacking, DEBUG_pos_x, DEBUG_pos_y, color)
	DEBUG_pos_y = DEBUG_pos_y - DEBUG_pos_y_diff
	
end



function on_input(self, action_id, action)

	if action.pressed then

		-------------
		if action_id == hash("space") then
			if self.attacking == 0 then
				self.attacking = 1
				self.direction.x = 0
				self.switch_anim = 1
			end
		end

		if action_id == hash("left") then
			--print("Left!")
			if self.direction.x == 0 then
				self.direction.x = -1
				if self.switch_anim == 0 then
					self.switch_anim = 1
				end
			end
		end

		if action_id == hash("right") then
			--print("Right!")
			if self.direction.x == 0 then
				self.direction.x = 1
				if self.switch_anim == 0 then
					self.switch_anim = 1
				end
			end
		end
		
	elseif action.released then

		if action_id == hash("right") or action_id == hash("left") then
			--print("Released!")
			
			if self.direction.x ~= 0 then
				self.direction.x = 0
			end
				
			if self.switch_anim == 0 then
				self.switch_anim = 1
			end
			
		end

	end

end



function on_message(self, message_id, message, sender)
	
	-- TEST EVENT
	if message_id == hash("spine_event") then
		-- Receiving animation event from Spine. Play footsteps.
		if message.event_id == hash("test") then
			--print("event test!!")
		end
	end

	-- ANIMATION DONE (attack)
	if message_id == hash("spine_animation_done") then
		if message.animation_id == hash(self.anim_attack_name) and message.playback == go.PLAYBACK_ONCE_FORWARD then
			if self.attacking == 2 then
				self.attacking = 0
				self.switch_anim = 1
				print("ATTACK anim finished!")
			end
		end
	end
	
end